# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Build"

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        cd 1-Authentication/1-sign-in/
        npm ci
        npm audit --production
        npm run test

    - run: |
        cd 1-Authentication/2-sign-in-b2c/
        npm ci
        npm audit --production
        npm run test

    - run: |
        cd 2-Authorization-I/1-call-graph/
        npm ci
        npm audit --production
        npm run test

    - run: |
        cd 3-Authorization-II/1-call-api/API
        npm ci
        npm audit --production
        npm run test

    - run: |
        cd 3-Authorization-II/1-call-api/SPA
        npm ci
        npm audit --production
        npm run test

    - run: |
        cd 3-Authorization-II/2-call-api-b2c/API
        npm ci
        npm audit --production
        npm run test

    - run: |
        cd 3-Authorization-II/2-call-api-b2c/SPA
        npm ci
        npm audit --production
        npm run test